[project]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "CLTheory"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = { version = "*", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
pytorch-cuda = { version = "*", channel = "pytorch" }
kornia = ">=0.6.0,<0.7"
ipykernel = ">=6.29.5,<7"
tqdm = ">=4.67.1,<5"
scikit-learn = ">=1.6.1,<2"
munkres = ">=1.1.4,<2"
matplotlib = ">=3.10.1,<4"
seaborn = ">=0.13.2,<0.14"
tensorboard = ">=2.20.0,<3"
